### PR TITLE
[Fixes 30] How to prevent Edge Swipe event?

### LINKED ISSUE #30: How to prevent Edge Swipe event?
Hello, MeTaNoV
I use this element building an app with `<paper-drawer-panel>`, that as follow

```
<paper-drawer-panel>
  <div drawer> Drawer panel... </div>
  <div main>
    <iron-swipeable-pages>...</iron-swipeable-pages>
  </div>
</paper-drawer-panel>
```
When I use this layout and swipe from edge of mobile screen,
the drawer will open by swipe normally, but problem is `<iron-swipeable-pages>` will also change page by the edge swipe action.

Is there have any way to prevent trigger the default Track event in Edge swipe?
(some thing like disableSwipe state or stopPropagation)

### PR DESCRIPTION
**Pull request by MeTaNoV**
Fixes #30 by:
- added an edge swipe sensitivity to avoid interference with paper-drawer-panel

---
This change is [Reviewable](https://reviewable.io/reviews/metanov/iron-swipeable-pages/31)

### CODE REVIEW

**Comment by MeTaNoV** [comment]
@JohnsonChung : could you test this branch before I merge it to master and release a new version?

**Comment by JohnsonChung** [comment]
Thank you! MeTaNoV
Really impressive efficient.

Now, will not Trigger the track by edge swipe,
new problem, when you swipe start from `SwipeAvailable area` to `edgeSwipeSensitivity area` that will cause pages stuck.

**Comment by JohnsonChung** [comment]
I always use  `startPointX = e.detail.x - e.detail.dx;` to check Down(track start) point to judge when should I return.

**Comment by JohnsonChung** [comment]
```if ((track.x - track.dx) < this.edgeSwipeSensitivity || (track.x - track.dx) > this.offsetWidth - this.edgeSwipeSensitivity) { return }```
work perfectly so far.

**Comment by MeTaNoV** [comment]
oh yes, thanks for pointing this out! I integrated your feedback, works as a charm now, Thanks!

**Pull request merged**
