### PR TITLE
Allow padding to be configured

### PR DESCRIPTION
**Pull request by rubenstolk**
This change is [Reviewable](https://reviewable.io/reviews/metanov/iron-swipeable-pages/13)

### CODE REVIEW

**Comment by MeTaNoV** [comment]
Hi @rubenstolk,
thanks for the PR, but I would like to fully understand the rationale, so can you point me to a visual example? If the element is embedded inside another element which includes a padding, it should not have normally any consequences on the area which will be visually swiped?
Cheers,
Pascal

**Comment by rubenstolk** [comment]
Hi @MeTaNoV. It's quite simple, suppose you have a box with a padding of 16px and inside of that you put `<iron-swipeable-pages>`. Suppose the box has a width of `832px`, that means that `<iron-swipeable-pages>`.offsetWidth is `800px`. Now, while swiping, the pages are positioned next to each other but you would expect the pages to have a padding of 32px in between them (16px to the right of page 1 and 16px to the left of page 2).

**Comment by MeTaNoV** [comment]
ok, so I understood it well, but my understanding is that they still should be positioned next to each other since the padding is defined on the parent. 
But if you want to be able to add an extra padding, why not and it does not interfere with a default to 0. Let's merge this! :)

**Comment by MeTaNoV** [comment]
@rubenstolk I also released a new version (`1.1.0`) of the component for you to reference!

**Comment by rubenstolk** [comment]
Great!

**Pull request merged**
