### PR TITLE
Allow resize event propagation to sub-elements

### PR DESCRIPTION
**Pull request by alemarre**
Propagates resize event to sub-elements, if they are contained in the current selected page

---
This change is [Reviewable](https://reviewable.io/reviews/metanov/iron-swipeable-pages/12)

### CODE REVIEW

**Comment by MeTaNoV** [comment]
Correct! Thanks!

**Comment by alemarre** [comment]
OK, I think it looks OK, but I'm not sure of the rebase
Tell me if you see anything wrong :)

**Comment by MeTaNoV** [comment]
looks fine, thanks! :)

**Comment by MeTaNoV** [comment]
@alemarre I also released a new version. And of course, if you find that element useful, do not hesitate to star it! ;)

**Comment by alemarre** [comment]
Thanks for your reactivity, I can delete my local patch :)
Yes of course, I starred your module, thanks for your work

**Pull request merged**
